### ISSUE TITLE
ERROR 5005

### ISSUE THREAD

**Issue by kinhosz** [foxbit-group/foxbit-api-samples#8]
```json
response = {'error': {'message': 'Price out of range from market.', 'code': 5005, 'details': ['The order price is out of range from market to complete your request.']}}
{}
```

Estou tentando criar uma ORDER LIMIT, contudo, independente do valor do preço que eu passe, sempre recebo este mesmo resultado. E não consigo encontrar nos docs qual o range esperado. Como prosseguir?

**Comment by marlon-chagas** [comment]
Bom dia, @kinhosz 

Em qual mercado estava tentando fazer a operação?
Seja qual for, os limites mínimos são descritos no endpoint de listagem de mercados [(/rest/v3/markets)](https://docs.foxbit.com.br/rest/v3/#tag/Market-Data/operation/MarketsController_index). Poderia validar se a quantidade enviada é a mesma ou acima da mínima para o mercado em questão?

**Comment by kinhosz** [comment]
Olá, @marlon-chagas, obrigado pela rápida resposta!

A título de curiosidade, estava no mercado 'btcbrl', contudo, por uma confusão de minha parte, entendi errado o valor errado do `price`. Eu achava que ele era relativo a _quanto eu queria gastar_ e não _qual valor 1 unidade de bitcoin deveria atingir_.
